project:
  type: website

website:
  title: "InflaWatch"
  repo-url: "https://github.com/darmatteoos/food_inflation_tracker"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/darmatteoos/food_inflation_tracker
        aria-label: InflaWatch GitHub


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

